name: Create Zip of tags

on:
  # Triggers the workflow for new tags
  # push:
  #   tags:
  #     - '**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get Branch name
        run: echo "BRANCH_NAME=$(echo $GITHUB_REF | sed -e "s|^refs/heads/||" | sed -e "s|^refs/tags/||" | sed -e "s/\<./\U&/g" )" >> $GITHUB_ENV
      - name: Display branch name
        run: echo ${{ env.BRANCH_NAME }}
      
      # Read version number from addon.xml
      - name: Read addon.xml
        id: addon
        uses: juliangruber/read-file-action@v1
        with:
          path: ./addon.xml
      - uses: kaisugi/action-regex-match@v1.0.0
        id: version-match
        with:
          text: ${{steps.addon.outputs.content}}
          regex: '<addon id=".*" version="([\d\.]+)"'
      
      # Create Zip
      - name: Zip Release
        uses: thedoctor0/zip-release@master
        with:
          type: zip
          filename: skin.quartz_${{steps.version-match.outputs.group1}}_${{ env.BRANCH_NAME }}.zip
          directory: .
          exclusions: '*.git*'

      - name: Directory listing for debugging
        run: ls -la

      # Create Release
      - name: Upload Release
        uses: ncipollo/release-action@main
        with:
          name: skin.quartz ${{steps.version-match.outputs.group1}} (${{ env.BRANCH_NAME }})
          allowUpdates: true
          prerelease: false
          removeArtifacts: true
          replacesArtifacts: true
          artifactErrorsFailBuild: true
          artifacts: skin.quartz_${{steps.version-match.outputs.group1}}_${{ env.BRANCH_NAME }}.zip
          artifactContentType: application/zip
          token: ${{secrets.GITHUB_TOKEN}}
